### ISSUE TITLE
sp_helpdb can not be found

### ISSUE THREAD

**Issue by solarisan2** [rodhoward/node-sybase#2]
I receive below error once trying to connect to sybase IQ database:

com.sybase.jdbc3.jdbc.SybSQLException: SQL Anywhere Error -265: Procedure 'sp_helpdb' not found

**Comment by bradenpowers** [comment]
I see this error as well.

**Comment by martvaha** [comment]
I think that Sybase IQ does not have the procedure 'sp_helpdb' and this project works only with Sybase AES.

There's a line in node_modules/sybase/JavaSybaseLink/src/SybaseDB.java:51:13 that calls this procedure. I don't know why it's being called, but if you remove it and recompile the Java source, it should work with Sybase IQ.

**Comment by rodhoward** [comment]
Thanks for your help Mart. I'm not sure why I put an sp_help in my code but
removing it sounds like the answer.

**Comment by rodhoward** [comment]
I have finally got back into my code and fixed up a few things. The reason that I had sp_help in the connect was to test the connection was fully working.  Not a great reason if its causing incompatibility with other versions of Sybase. I have taken it out so this issue should be fixed in version 1.0.9.
